version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - db-ntwk
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:

networks:
  db-ntwk:
    ipam:
      config:
        - subnet: 172.18.0.0/16

